# Generated by Django 5.1.3 on 2025-03-26 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('cost_per_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
                ('time_per_sqm', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='type_of_work',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.worktype'),
        ),
        migrations.DeleteModel(
            name='TypeOfWork',
        ),
    ]
