# Generated by Django 5.1.3 on 2025-03-29 14:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0003_worktype_alter_project_type_of_work_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SelectedWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('work_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.worktype')),
            ],
        ),
    ]
